name: f1
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - requests
  - pyyaml
  - pip
  - pip:
      - fastf1
      - kaggle
